### ISSUE TITLE
Node executable is not found on Linux

### ISSUE THREAD

**Issue by rangelfinal** [nxtep-io/ts-framework-cli#1]
The shebang `#!/usr/bin/env node` works as expected on Mac systems (It finds and runs the following code using the system node), but fails with a `No such file or directory` on Linux.
https://github.com/nxtep-io/ts-framework-cli/blob/179ba73f1e09fe35518414d290b8c24ad5341fcc/lib/bin.ts#L1

Manually running `/usr/bin/env node -v` on the console outputs `v10.9.0`, the same as `node -v`.

**Comment by luiseduardobrito** [comment]
Reopened for this problem is not fully fixed in current release.

**Comment by luiseduardobrito** [comment]
A new fix candidate was opened in #10

**Comment by luiseduardobrito** [comment]
PS: The solution implemented in #10 probably won't work for Windows based installations. This might be a case for a separate issue, a lot of things usually break for global binaries in Windows environments.

**Comment by rangelfinal** [comment]
Notice: There's a bug in VS Code that prevents the debugger from following the source maps when debugging with `ts-framework watch --inspect`.
More info here: https://github.com/nxtep-io/ts-framework-cli/pull/11/files

**Comment by luiseduardobrito** [comment]
I've updated the PR with a better shell script, without any IF/ELSE over the current unix platform and with node inspection support. Already tested and working under OSX / Debian based environments.

See: [v2.5.0](https://github.com/nxtep-io/ts-framework-cli/releases/tag/2.5.0)
